#!/bin/sh
### BEGIN INIT INFO
# Provides:          wifi-auto
# Required-Start:    $network
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: WiFi auto-connect script
### END INIT INFO

case "$1" in
  start)
    echo "Starting wifi-auto..."
    /usr/bin/wifi-auto
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|restart}"
    exit 1
esac

exit 0